---
- name: Init control plane node
  shell: >
    kubeadm init --apiserver-advertise-address={{ ip }} --pod-network-cidr=192.168.0.0/16 \
    | tee /vagrant/k8s_controlplane \
    | tail -n 2 \
    | tee /vagrant/kubeadm_join_command
  vars:
  - ip: "{{ ansible_eth1['ipv4']['address'] }}"

- name: Create .kube directory
  become: no
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
  register: kube_dir

- name: Copy kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kube_dir.path }}/config"
    remote_src: yes
    owner: vagrant
    group: vagrant

- name: Install Calico CNI
  become: no
  shell: "kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml"
